on: [push]

jobs:
  change_log_maintainance:
    runs-on: ubuntu-latest
    name: ChangeLog Update Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update ChangeLog
        uses: ./actions/ # uses the one in the action dir
        id: changelog
        with:
          who-to-greet: 'Mona the Octocat'
          changelog_filename: 'debian/changelog'
          config_file: 'debian/control'
          version_file:  'debian/version'
          mode_file: 'debian/mode'
          committer_username: 'Luis Leon'
          committer_email: 'lleon95@gmail.com'
          base_branch: 'HEAD~1'
